### ISSUE TITLE
Add an option to display transaction size in USD instead of BTC

### ISSUE THREAD

**Issue by lupine-dev** [MaxLaumeister/bitlisten#18]
Within each bubble, the transaction size is currently displayed in BTC. A UI toggle could make it so that these transaction sizes are displayed in USD. This would make it easier to see how large transactions are at a glance.

**Comment by MalcolmA** [comment]
https://github.com/MaxLaumeister/bitlisten/pull/19

**Comment by lupine-dev** [comment]
Pull request merged!
